# windows/menu_ext/rez_env_manager.py
#
# 「Setting > KDM Rez Manager...」メニューを追加し、
# rez 用のパッケージを
#   %LOCALAPPDATA%/KDMres/packages
# 以下に自動生成・一覧表示するダイアログを提供する。
#
# 既存コードは一切変更しない想定。

import os
import re
import sys
from pathlib import Path
from typing import List, Optional, Tuple

from PySide2.QtCore import Qt
from PySide2.QtGui import QDesktopServices
from PySide2.QtWidgets import (
    QDialog,
    QDialogButtonBox,
    QHBoxLayout,
    QLabel,
    QListWidget,
    QListWidgetItem,
    QMessageBox,
    QPushButton,
    QVBoxLayout,
    QWidget,
)
from PySide2.QtCore import QUrl

from ..menu_api import MenuRegistrar  # type: ignore


# ------------------------------------------------------------
# ユーティリティ
# ------------------------------------------------------------

def _get_kdmres_root() -> Path:
    """
    KDMres のルートディレクトリを返す。

    通常は:
        %LOCALAPPDATA%/KDMres
    が利用される。
    """
    local_appdata = os.environ.get("LOCALAPPDATA")
    if not local_appdata:
        # LOCALAPPDATA が取れない環境向けのフォールバック
        home = Path.home()
        local_appdata = str(home / "AppData" / "Local")

    root = Path(local_appdata) / "KDMres"
    root.mkdir(parents=True, exist_ok=True)
    return root


def _extract_version_from_name(name: str) -> str:
    """
    ディレクトリ名などから数字部分を抽出してバージョン文字列にする簡易ヘルパー。

    例:
        'Maya2026' -> '2026'
        'Houdini20.5' -> '20.5' （簡易対応で '205' になる可能性もある）
    """
    # 数字とドットをそれっぽくくっつける簡易実装
    # 本格的にやる場合は個別ツールごとにパーサーを書く。
    matches = re.findall(r"\d+(?:\.\d+)?", name)
    if not matches:
        return "1.0.0"
    # とりあえず先頭だけ使う
    return matches[0]


def _ensure_package_dir(name: str, version: str) -> Path:
    """
    KDMres 配下に packages/<name>/<version>/ ディレクトリを作成し、そのパスを返す。
    """
    root = _get_kdmres_root()
    package_dir = root / "packages" / name / version
    package_dir.mkdir(parents=True, exist_ok=True)
    return package_dir


def _generate_maya_package(exe_path: Path) -> Tuple[str, str, str]:
    """
    Maya の exe パスから rez パッケージの name / version / body を生成する。
    """
    # 例: C:/Program Files/Autodesk/Maya2026/bin/maya.exe
    maya_root = exe_path.parents[1]  # .../Maya2026/
    version = _extract_version_from_name(maya_root.name)
    name = "maya"

    bin_path = str(maya_root / "bin").replace("\\", "/")

    body = f'''# Auto-generated by KDM Rez Manager
name = "{name}"
version = "{version}"

def commands():
    # Maya の bin ディレクトリを PATH の先頭に追加
    env.PATH.prepend(r"{bin_path}")
'''
    return name, version, body


def _generate_python_package(exe_path: Path) -> Tuple[str, str, str]:
    """
    Python の exe パスから rez パッケージの name / version / body を生成する。
    """
    # 例: C:/Users/xxx/AppData/Local/Programs/Python/Python312/python.exe
    py_root = exe_path.parent  # .../Python312/
    version = _extract_version_from_name(py_root.name)
    name = "python"

    bin_path = str(py_root).replace("\\", "/")

    body = f'''# Auto-generated by KDM Rez Manager
name = "{name}"
version = "{version}"

def commands():
    # Python フォルダを PATH の先頭に追加
    env.PATH.prepend(r"{bin_path}")
'''
    return name, version, body


def _find_maya_executables() -> List[Path]:
    """
    Windows の標準インストールパスから Maya の exe を簡易検出する。

    実運用では環境に合わせて拡張する前提のラフな実装。
    """
    results: List[Path] = []

    program_files = os.environ.get("PROGRAMFILES", r"C:\Program Files")
    autodesk_root = Path(program_files) / "Autodesk"
    if autodesk_root.is_dir():
        for child in autodesk_root.iterdir():
            # MayaXXXX っぽいディレクトリを対象
            if not child.is_dir():
                continue
            if "Maya" not in child.name:
                continue
            maya_exe = child / "bin" / "maya.exe"
            if maya_exe.is_file():
                results.append(maya_exe)

    return results


def _find_python_executables() -> List[Path]:
    """
    よくある Python インストールパスをいくつか見に行って python.exe を探す。
    """
    results: List[Path] = []

    # 1) このプロセスの Python
    this_python = Path(sys.executable)
    if this_python.name.lower() == "python.exe" and this_python.is_file():
        results.append(this_python)

    # 2) %LOCALAPPDATA%/Programs/Python/*
    local_appdata = os.environ.get("LOCALAPPDATA")
    if local_appdata:
        py_root = Path(local_appdata) / "Programs" / "Python"
        if py_root.is_dir():
            for child in py_root.iterdir():
                if not child.is_dir():
                    continue
                exe = child / "python.exe"
                if exe.is_file():
                    results.append(exe)

    # 重複排除
    unique: List[Path] = []
    seen = set()
    for p in results:
        key = str(p.resolve()).lower()
        if key in seen:
            continue
        seen.add(key)
        unique.append(p)

    return unique


# ------------------------------------------------------------
# ダイアログ本体
# ------------------------------------------------------------

class RezEnvManagerDialog(QDialog):
    """
    KDM Rez Manager ダイアログ。

    - KDMres 配下の packages を一覧表示
    - Maya / Python を簡易スキャンして rez package.py を自動生成
    - 選択パッケージのフォルダを Explorer で開く
    """

    def __init__(self, parent: Optional[QWidget] = None) -> None:
        super().__init__(parent)
        self.setWindowTitle("KDM Rez Manager")
        self.resize(640, 420)

        self._root = _get_kdmres_root()
        self._packages_root = self._root / "packages"

        self._setup_ui()
        self._refresh_package_list()

    # --------------------------------------------------------
    # UI セットアップ
    # --------------------------------------------------------
    def _setup_ui(self) -> None:
        layout = QVBoxLayout(self)

        # 説明 + ルートパス表示
        info_label = QLabel(
            "Windows 標準パスから Maya / Python を簡易検出し、\n"
            "rez パッケージ定義を KDMres 配下に自動生成します。",
            self,
        )
        info_label.setWordWrap(True)

        root_label = QLabel(
            f"KDMres Root: {str(self._root)}",
            self,
        )
        root_label.setTextInteractionFlags(Qt.TextSelectableByMouse)

        layout.addWidget(info_label)
        layout.addWidget(root_label)

        # パッケージ一覧
        self._list = QListWidget(self)
        layout.addWidget(self._list, 1)

        # ボタン群
        button_row = QHBoxLayout()
        self._scan_button = QPushButton("スキャンしてパッケージ化", self)
        self._open_button = QPushButton("選択フォルダを開く", self)

        button_row.addWidget(self._scan_button)
        button_row.addWidget(self._open_button)
        button_row.addStretch(1)

        layout.addLayout(button_row)

        # 下部の Close ボタン
        button_box = QDialogButtonBox(QDialogButtonBox.Close, parent=self)
        layout.addWidget(button_box)

        # シグナル接続
        self._scan_button.clicked.connect(self._on_scan_and_create)
        self._open_button.clicked.connect(self._on_open_selected)
        button_box.rejected.connect(self.reject)
        button_box.accepted.connect(self.accept)

    # --------------------------------------------------------
    # パッケージ一覧
    # --------------------------------------------------------
    def _refresh_package_list(self) -> None:
        """
        KDMres/packages 以下の package.py を走査して QListWidget に反映する。
        """
        self._list.clear()

        if not self._packages_root.is_dir():
            return

        for name_dir in sorted(self._packages_root.iterdir()):
            if not name_dir.is_dir():
                continue
            name = name_dir.name
            for ver_dir in sorted(name_dir.iterdir()):
                if not ver_dir.is_dir():
                    continue
                version = ver_dir.name
                package_py = ver_dir / "package.py"
                if not package_py.is_file():
                    continue

                item = QListWidgetItem(f"{name}-{version}")
                # UserRole にフォルダパスを持たせる
                item.setData(Qt.UserRole, str(ver_dir))
                self._list.addItem(item)

    # --------------------------------------------------------
    # スキャン & パッケージ生成処理
    # --------------------------------------------------------
    def _on_scan_and_create(self) -> None:
        created: List[str] = []
        skipped: List[str] = []

        # Maya
        for maya_exe in _find_maya_executables():
            name, version, body = _generate_maya_package(maya_exe)
            pkg_dir = _ensure_package_dir(name, version)
            pkg_file = pkg_dir / "package.py"
            if pkg_file.is_file():
                skipped.append(f"{name}-{version} (Maya)")
                continue
            pkg_file.write_text(body, encoding="utf-8")
            created.append(f"{name}-{version} (Maya)")

        # Python
        for py_exe in _find_python_executables():
            name, version, body = _generate_python_package(py_exe)
            pkg_dir = _ensure_package_dir(name, version)
            pkg_file = pkg_dir / "package.py"
            if pkg_file.is_file():
                skipped.append(f"{name}-{version} (Python)")
                continue
            pkg_file.write_text(body, encoding="utf-8")
            created.append(f"{name}-{version} (Python)")

        self._refresh_package_list()

        # 結果をダイアログ表示
        msg_lines: List[str] = []
        if created:
            msg_lines.append("作成されたパッケージ:")
            msg_lines.extend(f"  - {c}" for c in created)
        if skipped:
            if msg_lines:
                msg_lines.append("")
            msg_lines.append("既に存在していたためスキップされたパッケージ:")
            msg_lines.extend(f"  - {s}" for s in skipped)
        if not msg_lines:
            msg_lines.append("新しく作成されたパッケージはありません。")

        QMessageBox.information(self, "KDM Rez Manager", "\n".join(msg_lines))

    # --------------------------------------------------------
    # 選択パッケージを Explorer で開く
    # --------------------------------------------------------
    def _on_open_selected(self) -> None:
        item: Optional[QListWidgetItem] = self._list.currentItem()
        if not item:
            QMessageBox.warning(self, "KDM Rez Manager", "パッケージが選択されていません。")
            return

        folder = item.data(Qt.UserRole)
        if not folder:
            return

        path = Path(folder)
        if not path.is_dir():
            QMessageBox.warning(self, "KDM Rez Manager", "フォルダが存在しません。")
            return

        # OS 依存の開き方。Windows 前提で Explorer を開く。
        try:
            QDesktopServices.openUrl(QUrl.fromLocalFile(str(path)))
        except Exception:
            # フォールバック
            os.startfile(str(path))  # type: ignore[attr-defined]


# ------------------------------------------------------------
# MenuRegistrar から呼ばれるエントリポイント
# ------------------------------------------------------------

def register_menus(registrar: MenuRegistrar) -> None:
    """
    menu_ext から呼ばれるメニュー登録関数。

    Setting メニュー配下に
        'KDM Rez Manager...'
    を追加し、RezEnvManagerDialog をモーダルで起動する。
    """

    def open_rez_manager_dialog() -> None:
        # MenuRegistrar が内部に _window を持っている前提で親を取得
        parent = getattr(registrar, "_window", None)
        dlg = RezEnvManagerDialog(parent=parent)
        dlg.exec_()

    # 「Setting > KDM Rez Manager...」を追加
    registrar.add_action(
        "Setting",
        "KDM Rez Manager...",
        open_rez_manager_dialog,
    )
